variable "cluster_name" {
  type = string
}

variable "kubeconfig_path" {
  type        = string
  description = "Path to the kubeconfig file generated by the 01-infra stage."
}

variable "kubeconfig_context" {
  type = string
}

## Longhorn Start

variable "longhorn_namespace" {
  type = string
}

variable "longhorn_version" {
  type = string
}

variable "longhorn_s3_endpoint" {
  type = string
}

## Longhorn End

## Tailscale Start

variable "tailscale_operator_namespace" {
  type = string
}

variable "tailscale_operator_chart_version" {
  type        = string
  description = "Version of the Tailscale Operator Helm chart to install. Check Tailscale docs for latest stable."
}

## Tailscale End

## Cloud Native PostgreSQL Start

variable "cnpg_operator_namespace" {
  type = string
}

variable "cnpg_operator_version" {
  type = string
}

## Cloud Native PostgreSQL End

## Cloudflare Start

variable "cloudflared_version" {
  type = string
}

variable "cloudflared_helm_chart_version" {
  type = string
}

variable "cloudflared_namespace" {
  type = string
}

variable "cloudflare_tunnel_name" {
  type = string
}

variable "cloudflare_tunnel_svcs" {
  description = "A list of services to expose, their external hostname and internal service address"
  type = list(object({
    hostname    = string
    service_uri = string
  }))
}

## Cloudflare End

## Immich Start

variable "immich_namespace" {
  type = string
}

variable "immich_chart_version" {
  type = string
}

variable "immich_version" {
  type = string
}

## Immich End

## Traefik Start

variable "traefik_namespace" {
  type = string
}

variable "traefik_version" {
  type = string
}

## Traefik End

## Speed Test Start

variable "openspeedtest_namespace" {
  type = string
}

variable "openspeedtest_chart_version" {
  type = string
}

## Speed Test End

## Firefly III Start

variable "firefly_namespace" {
  type = string
}

variable "firefly_chart_version" {
  type = string
}

## Firefly III End

## Kubescape Start

variable "kubescape_namespace" {
  type = string
}

variable "kubescape_chart_version" {
  type = string
}

## Kubescape End

## Monitoring Start

variable "kube_prometheus_stack_version" {
  type = string
}

## Monitoring End

## Plane Start

# variable "plane_namespace" {
#   type = string
# }
#
# variable "plane_chart_version" {
#   type = string
# }
#
# variable "plane_version" {
#   type = string
# }

## Plane End