grafana:
  persistence:
    enabled: true

  envFromConfigMaps:
    - name: grafana-cloudflare-auth
      optional: false

prometheus-node-exporter:
  prometheusSpec:
    scrapeInterval: 10s

prometheus:
  prometheusSpec:
    retention: 365d
    retentionSize: 35GB
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteMany"]
          resources:
            requests:
              storage: 40Gi
    # Allow PodMonitors and ServiceMonitors to be created in any namespace.
    podMonitorNamespaceSelector:
      matchLabels: { }
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector:
      matchLabels: { }
    serviceMonitorSelectorNilUsesHelmValues: false